manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main          # for stability you can pin this to a release tag, e.g. v0.3
      import: app/west.yml
  self:
    path: config
